# Numpy and Pandas Essentials

**This notebook is a compilation of some essential concepts of Numpys and Pandas which is used for data processing and model evaluation**

## Numpy 

** This library is one of the most famous and important one for python development this library focus on mainly numerical calculation part of the data it is based on and for calculating the data **

In [1]:
#importing the libraries to this workspace 
import numpy as np
import pandas as pd

In [2]:
#visualizing numpy in action 
array = np.array([1,4,5,8],dtype=float)
print(array," ")
array = np.array([[1,2,3],[4,5,6]],float) # 2D array 
print(array)

[1. 4. 5. 8.]  
[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
#array indexing and slicing in action
array = np.array([1, 4, 5, 8], float)
print(array)
print("",array[1])
print(array[:2])
array[1]=5.0
print(array[1])

[1. 4. 5. 8.]
 4.0
[1. 4.]
5.0


In [4]:
# matrix indexing and slicing
two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
print(two_D_array)
print(two_D_array[1][1])
print(two_D_array[1,:])
print(two_D_array[:,2])

[[1. 2. 3.]
 [4. 5. 6.]]
5.0
[4. 5. 6.]
[3. 6.]


In [5]:
#performing some basic arithmetic operations on array 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)

print(array_1+array_2)
print(np.subtract(array_1,array_2))
print(np.dot(array_1,array_2))

[6. 4. 9.]
[-4.  0. -3.]
27.0


In [6]:
#performing some basic for mean and dot products 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)
print(np.mean(array_1))
print(np.mean(array_2))

print(np.dot(array_1,array_2))

2.0
7.0
[44.]


## Pandas 
** This is the library developed over numpys and its mainly used for data segeregation and viewing in the form of Tables and series of an array **

### Series 

In [7]:
# printing series made of Pandas data series  

series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
print (series)

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object


In [8]:
# printing series based on custom index 
series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
print(series)

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object


In [9]:
# selecting a value of data element using its index values 
print(series['Instructor'])
print(series[['Instructor', 'Curriculum Manager', 'Course Number']])

Dave
Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object


In [10]:
# selecting values using boolean values 
cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
print(cuteness > 3)
print(cuteness[cuteness > 3])

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
Puppy     4
Kitten    5
dtype: int64


### DataFrame 
** This is a two dimensional data frame which can be related to an Excel sheet where data is been stored in a form of tables and composite data structure can be included into the whole data set  **

In [11]:
# Data Frame in action 
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)
football

losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012

In [12]:
# performing some functions on DataFrames 

print(football.dtypes)
print(football.describe())
print(football.head())
print(football.tail())

losses     int64
team      object
wins       int64
year       int64
dtype: object
          losses       wins         year
count   8.000000   8.000000     8.000000
mean    6.625000   9.375000  2011.125000
std     3.377975   3.377975     0.834523
min     1.000000   4.000000  2010.000000
25%     5.000000   7.500000  2010.750000
50%     6.000000  10.000000  2011.000000
75%     8.500000  11.000000  2012.000000
max    12.000000  15.000000  2012.000000
   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012
