# Numpy and Pandas Essentials

**This notebook is a compilation of some essential concepts of Numpys and Pandas which is used for data processing and model evaluation**

## Numpy 

** This library is one of the most famous and important one for python development this library focus on mainly numerical calculation part of the data it is based on and for calculating the data **

In [1]:
#importing the libraries to this workspace 
import numpy as np
import pandas as pd

In [2]:
#visualizing numpy in action 
array = np.array([1,4,5,8],dtype=float)
print(array," ")
array = np.array([[1,2,3],[4,5,6]],float) # 2D array 
print(array)

[1. 4. 5. 8.]  
[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
#array indexing and slicing in action
array = np.array([1, 4, 5, 8], float)
print(array)
print("",array[1])
print(array[:2])
array[1]=5.0
print(array[1])

[1. 4. 5. 8.]
 4.0
[1. 4.]
5.0


In [4]:
# matrix indexing and slicing
two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
print(two_D_array)
print(two_D_array[1][1])
print(two_D_array[1,:])
print(two_D_array[:,2])

[[1. 2. 3.]
 [4. 5. 6.]]
5.0
[4. 5. 6.]
[3. 6.]


In [5]:
#performing some basic arithmetic operations on array 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)

print(array_1+array_2)
print(np.subtract(array_1,array_2))
print(np.dot(array_1,array_2))

[6. 4. 9.]
[-4.  0. -3.]
27.0


In [6]:
#performing some basic for mean and dot products 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)
print(np.mean(array_1))
print(np.mean(array_2))

print(np.dot(array_1,array_2))

2.0
7.0
[44.]


## Pandas 
** This is the library developed over numpys and its mainly used for data segeregation and viewing in the form of Tables and series of an array **

### Series 

In [7]:
# printing series made of Pandas data series  

series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
print (series)

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object


In [8]:
# printing series based on custom index 
series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
print(series)

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object


In [9]:
# selecting a value of data element using its index values 
print(series['Instructor'])
print(series[['Instructor', 'Curriculum Manager', 'Course Number']])

Dave
Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object


In [10]:
# selecting values using boolean values 
cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
print(cuteness > 3)
print(cuteness[cuteness > 3])

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
Puppy     4
Kitten    5
dtype: int64


### DataFrame 
** This is a two dimensional data frame which can be related to an Excel sheet where data is been stored in a form of tables and composite data structure can be included into the whole data set  **

In [11]:
# Data Frame in action 
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)
football

losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012

In [12]:
# performing some functions on DataFrames 

print(football.dtypes)
print(football.describe())
print(football.head())
print(football.tail())

losses     int64
team      object
wins       int64
year       int64
dtype: object
          losses       wins         year
count   8.000000   8.000000     8.000000
mean    6.625000   9.375000  2011.125000
std     3.377975   3.377975     0.834523
min     1.000000   4.000000  2010.000000
25%     5.000000   7.500000  2010.750000
50%     6.000000  10.000000  2011.000000
75%     8.500000  11.000000  2012.000000
max    12.000000  15.000000  2012.000000
   losses     team  wins  year
0       5    Bears    11  2010
1       8    Bears     8  2011
2       6    Bears    10  2012
3       1  Packers    15  2011
4       5  Packers    11  2012
   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
5      10    Lions     6  2010
6       6    Lions    10  2011
7      12    Lions     4  2012


In [13]:
# Creating a data frame using pandas 
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']
gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]

olympic_medal_counts = {'country_name':pd.Series(countries),'gold_medals':pd.Series(gold),
        'silver_medals':pd.Series(silver),'bronze_medals':pd.Series(bronze)}
olympic_medal_counts_df = pd.DataFrame(olympic_medal_counts)
olympic_medal_counts_df

bronze_medals    country_name  gold_medals  silver_medals
0               9    Russian Fed.           13             11
1              10          Norway           11              5
2               5          Canada           10             10
3              12   United States            9              7
4               9     Netherlands            8              7
5               5         Germany            8              6
6               2     Switzerland            6              3
7               1         Belarus            5              0
8               5         Austria            4              8
9               7          France            4              4
10              1          Poland            4              1
11              2           China            3              4
12              2           Korea            3              3
13              6          Sweden            2              7
14              2  Czech Republic            2              4
15              4        Slovenia            2              2
16              3           Japan            1              4
17              1         Finland            1              3
18              2   Great Britain            1              1
19              1         Ukraine            1              0
20              0        Slovakia            1              0
21              6           Italy            0              2
22              2          Latvia            0              2
23              1       Australia            0              2
24              0         Croatia            0              1
25              1      Kazakhstan            0              0

### Indexing DataFrame 
Indexing is one of the most important concept in DataFrame it is the backbone as it helps in traversing the DataFrame according to the condition requirement

In [15]:
# Series indexing in the action 
data = {'year': [2010, 2011, 2012, 2011, 2012, 2010, 2011, 2012],
            'team': ['Bears', 'Bears', 'Bears', 'Packers', 'Packers', 'Lions',
                     'Lions', 'Lions'],
            'wins': [11, 8, 10, 15, 11, 6, 10, 4],
            'losses': [5, 8, 6, 1, 5, 10, 6, 12]}
football = pd.DataFrame(data)
print(football['year'])
print(football.year) #short hand for football['year']
print(football[['year','wins','losses']])

0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64
0    2010
1    2011
2    2012
3    2011
4    2012
5    2010
6    2011
7    2012
Name: year, dtype: int64
   year  wins  losses
0  2010    11       5
1  2011     8       8
2  2012    10       6
3  2011    15       1
4  2012    11       5
5  2010     6      10
6  2011    10       6
7  2012     4      12


```
Row selection can be done through multiple ways.

Some of the basic and common methods are:
   1) Slicing
   2) An individual index (through the functions iloc or loc)
   3) Boolean indexing

You can also combine multiple selection requirements through boolean
operators like & (and) or | (or)
```

In [19]:
# Boolean indexing in the action 
print(football.iloc[0])
print("")
print(football.loc[0])
print("")
print(football[3:5])
print("")
print(football[football.wins > 10])
print("")
print(football[(football.wins > 10) & (football.team == "Packers")])

losses        5
team      Bears
wins         11
year       2010
Name: 0, dtype: object

losses        5
team      Bears
wins         11
year       2010
Name: 0, dtype: object

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
0       5    Bears    11  2010
3       1  Packers    15  2011
4       5  Packers    11  2012

   losses     team  wins  year
3       1  Packers    15  2011
4       5  Packers    11  2012
