# Numpy and Pandas Essentials

**This notebook is a compilation of some essential concepts of Numpys and Pandas which is used for data processing and model evaluation**

## Numpy 

** This library is one of the most famous and important one for python development this library focus on mainly numerical calculation part of the data it is based on and for calculating the data **

In [1]:
#importing the libraries to this workspace 
import numpy as np
import pandas as pd

In [2]:
#visualizing numpy in action 
array = np.array([1,4,5,8],dtype=float)
print(array," ")
array = np.array([[1,2,3],[4,5,6]],float) # 2D array 
print(array)

[1. 4. 5. 8.]  
[[1. 2. 3.]
 [4. 5. 6.]]


In [3]:
#array indexing and slicing in action
array = np.array([1, 4, 5, 8], float)
print(array)
print("",array[1])
print(array[:2])
array[1]=5.0
print(array[1])

[1. 4. 5. 8.]
 4.0
[1. 4.]
5.0


In [4]:
# matrix indexing and slicing
two_D_array = np.array([[1, 2, 3], [4, 5, 6]], float)
print(two_D_array)
print(two_D_array[1][1])
print(two_D_array[1,:])
print(two_D_array[:,2])

[[1. 2. 3.]
 [4. 5. 6.]]
5.0
[4. 5. 6.]
[3. 6.]


In [5]:
#performing some basic arithmetic operations on array 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([5, 2, 6], float)

print(array_1+array_2)
print(np.subtract(array_1,array_2))
print(np.dot(array_1,array_2))

[6. 4. 9.]
[-4.  0. -3.]
27.0


In [6]:
#performing some basic for mean and dot products 
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)
print(np.mean(array_1))
print(np.mean(array_2))

print(np.dot(array_1,array_2))

2.0
7.0
[44.]


## Pandas 
** This is the library developed over numpys and its mainly used for data segeregation and viewing in the form of Tables and series of an array **

### Series 

In [7]:
# printing series made of Pandas data series  

series = pd.Series(['Dave', 'Cheng-Han', 'Udacity', 42, -1789710578])
print (series)

0           Dave
1      Cheng-Han
2        Udacity
3             42
4    -1789710578
dtype: object


In [8]:
# printing series based on custom index 
series = pd.Series(['Dave', 'Cheng-Han', 359, 9001],
                       index=['Instructor', 'Curriculum Manager',
                              'Course Number', 'Power Level'])
print(series)

Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
Power Level                9001
dtype: object


In [9]:
# selecting a value of data element using its index values 
print(series['Instructor'])
print(series[['Instructor', 'Curriculum Manager', 'Course Number']])

Dave
Instructor                 Dave
Curriculum Manager    Cheng-Han
Course Number               359
dtype: object


In [10]:
# selecting values using boolean values 
cuteness = pd.Series([1, 2, 3, 4, 5], index=['Cockroach', 'Fish', 'Mini Pig',
                                                 'Puppy', 'Kitten'])
print(cuteness > 3)
print(cuteness[cuteness > 3])

Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
Puppy     4
Kitten    5
dtype: int64
